blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.BlogView.as_view(), name='blog'),
    path('blog/<slug>/', views.BlogDetailView.as_view(), name="blog-detail"),


]

core/urls.py
from django.urls import path, include
from . import views

app_name = "core"


urlpatterns = [
    path('list/', views.ListView.as_view(), name="list"),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('newsletter/', views.NewsletterView.as_view(), name="newsletter"),
    path('add-to-cart/', views.AddToCartView.as_view(), name="add-to-cart"),
    path('order-summary/', views.OrderDetailView.as_view(), name="order-summary"),
    path('order-item/delete/',
         views.OrderItemDeleteView.as_view(), name="order-item-delete"),
    path('order-item/update-quantity/', views.OrderQuantityupdateView.as_view(),
         name="order-item-update-quantity"),
    path('address-list/', views.AddressListView.as_view(), name="Address-list"),
    path('address/create/', views.AddressCreateView.as_view(), name="address-create"),
    path('product/<slug>/', views.ProductDetailsView.as_view(),
         name="product-details"),
    path('check-wishlist/', views.CheckWishlistView.as_view(),
         name="check-wishlist"),
    path('wishlist/', views.AddToWishListView.as_view(),
         name="wishlist"),
    path('review/', views.CreateReviewView.as_view(),
         name="review"),
    path('check-review/', views.CheckReviewsView.as_view(),
         name="check-review"),
    path('check-tags/', views.CheckTagsView.as_view(),
         name="check-tags"),
    path('add-coupon/', views.AddCouponView.as_view(),
         name="add-coupon"),
    path('paystackkey/', views.PaystackkeyView.as_view(), name='paystack'),
    path('user-email/', views.UserEmailView.as_view(), name='user-email'),
    path('fetch-saved/', views.FetchWishlistView.as_view(), name='fetch-saved'),
    path('delete-saved/', views.DeleteFromWishlistView.as_view(), name='delete-saved'),
    path('shipping-fee/', views.ShippingFeeVIew.as_view(), name='shipping-fee'),
    path('add-shipping-fee/', views.AddShippingFeeView.as_view(),
         name='add-shipping-fee'),
    path('payment-done/', views.PaymentCreateView.as_view(),
         name='payment-done'),
    path('ordered-items/', views.OrderedItemsView.as_view(),
         name='ordered-items'),
    path('delete-address/', views.DeleteAddressView.as_view(),
         name='delete-address'),
    path('get-order-details/', views.CheckOrderDetailsView.as_view(),
         name="get-order-details"),
    path('get-order-item-details/', views.CheckOrderItemDetailsView.as_view(),
         name="get-order-items-details"),
    path('get-user/', views.UserDetailsView.as_view(), name="get-user"),
    path('related-post/', views.RelatedPostView.as_view(), name="related-post"),
    path('default-address/', views.DefaultAddressListView.as_view(),
         name="default-address"),

    path('default-shipping-fee/',
         views.DefaultShippingFeeVIew.as_view(), name='shipping-fee'),
    path('add-default-shipping-fee/', views.AddDefaultShippingFeeView.as_view(),
         name='add-shipping-fee'),
    path('address/create/default/',
         views.AddressDefaultCreateView.as_view(), name="address-create"),
    path('payment-check/',
         views.PaymentCheckView.as_view(), name="payment-check"),
    path('shop/',
         views.ShopListView.as_view(), name="shop"),
    path('shop-search/',
         views.SearchView.as_view(), name="shop-search"),
   path('recent-viewed/',
         views.RecentView.as_view(), name="recent-viewed"),
         




































]

jane_new/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [

    path('account/reset/<uidb64>/<token>/',
         TemplateView.as_view(template_name="password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('admin/', admin.site.urls),
    path('api/', include('core.urls')),
    path('accounts/', include('allauth.urls')),
    path("paystack", include(('paystack.urls', 'paystack'), namespace='paystack')),
    path('blog/', include('blog.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('rest-auth/', include('dj_rest_auth.urls')),
    path('rest-auth/registration/', include('dj_rest_auth.registration.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

paystack/urls.py
from . import views
from . import settings
from django.views.decorators.csrf import csrf_exempt
import django

version = django.get_version().split(".")
if int(version[0]) >= 2:
    from django.urls import re_path as url
else:
    from django.conf.urls import url


urlpatterns = [
    url(
        r"^verify-payment/(?P<order>[\w.@+-]+)/$",
        views.verify_payment,
        name="verify_payment",
    ),
    url(
        r"^failed-verification/(?P<order_id>[\w.@+-]+)/$",
        views.failure_redirect_view,
        name="failed_verification",
    ),
    url(
        r"^successful-verification/(?P<order_id>[\w.@+-]+)/$",
        views.success_redirect_view,
        name="successful_verification",
    ),
    url(
        r"^failed-page/$",
        views.TemplateView.as_view(template_name="paystack/failed-page.html"),
        name="failed_page",
    ),
    url(
        r"^success-page/$",
        views.TemplateView.as_view(template_name="paystack/success-page.html"),
        name="success_page",
    ),
    url(r"^webhook/$", csrf_exempt(views.webhook_view), name="webhook"),
]

core/models.py
from django.db.models.fields.related import ForeignKey
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import AbstractUser
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField


FEATURE_CHOICES = (
    ('none', 'None'),
    ('featured_accessories', 'Featured Accessories'),
    ('featured_bags', 'Featured Bags'),
    ('featured_clothing', 'Featured Clothing'),
    ('featured_footwear', 'Featured Footwear'),


)


COLOR = (
    ('black', 'Black'),
    ('white', 'White'),
    ('red', 'Red'),
    ('pink', 'Pink'),
    ('green', 'Green'),
    ('purple', 'Purple'),
    ('brown', 'Brown'),




)


class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username


class Category(models.Model):
    name = models.CharField(max_length=250, blank=True)
    slug = models.SlugField(max_length=250)

    class Meta:
        unique_together = ['name', 'slug']
        ordering = ['name']
        verbose_name_plural = 'categories'

    def get_category_url(self):
        return reverse("core:categoryview", kwargs={
            'slug': self.slug
        })

    def __str__(self):
        return self.name

    @property
    def get_category_count(self):
        return self.item_set.all().count()


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    new_arrival = models.BooleanField(default=False, blank=True, null=True)
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE)
    color = models.CharField(
        choices=COLOR, max_length=1000, blank=True,  null=True)
    label = models.CharField(choices=FEATURE_CHOICES, max_length=1000)
    slug = models.SlugField()
    description = RichTextField(blank=True,  null=True)
    size_chart = models.ImageField(blank=True,  null=True)
    image = models.ImageField()
    image_1 = models.ImageField(blank=True,  null=True)
    image_2 = models.ImageField(blank=True,  null=True)
    image_3 = models.ImageField(blank=True,  null=True)
    image_4 = models.ImageField(blank=True,  null=True)
    tags = TaggableManager()
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        unique_together = ['title', 'slug']

    def get_percentage(self):
        if self.discount_price:
            percent = self.discount_price - self.price
            return percent / 100

    @property
    def get_reviews_count(self):
        return self.reviews_set.all().count()

    @property
    def get_reviews(self):
        return self.reviews_set.all()


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    order_price = models.CharField(max_length=200, blank=True, null=True)
    order_final_price = models.CharField(max_length=200, blank=True, null=True)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    shipping_fee = models.FloatField(blank=False, null=True)

    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    payment_reference = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

    def get_order_total(self):
        total = self.get_total()
        if self.coupon:
            total -= self.coupon.amount
            return total
        return total

    def get_order_final_total(self):
        total = self.get_order_total()
        if self.shipping_fee:
            total += self.shipping_fee
            return total
        return total


def add_ref_code(sender, instance, created, *args, **kwargs):
    if created:
        instance.ref_code = instance.id
        instance.save()


post_save.connect(add_ref_code, sender=Order)


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    address = models.TextField(blank=False, null=True)
    country = models.CharField(max_length=100, blank=False, null=True)
    zip = models.CharField(max_length=100, blank=True, null=True)
    phone = models.CharField(max_length=100, blank=False, null=True)
    state = models.CharField(max_length=255, blank=False, null=True)
    default = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True, blank=False, null=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    reference = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15, blank=False, null=True)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)


class Slider(models.Model):
    title = models.CharField(max_length=20, blank=True, null=True)
    text = models.CharField(max_length=20, blank=True, null=True)
    image = models.ImageField()
    link = models.URLField(max_length=200, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.title


class HomepageBanner(models.Model):
    image = models.ImageField()
    link = models.URLField(blank=True, null=True)
    title = models.CharField(blank=True, null=True, max_length=100)
    description = models.CharField(blank=True, null=True, max_length=100)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Image"


class About(models.Model):
    link = models.URLField(blank=True, null=True)
    title = models.CharField(blank=True, null=True, max_length=100)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class HomesideBanner(models.Model):
    image = models.ImageField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Image"


class ShoptopBanner(models.Model):
    image = models.ImageField()
    title = models.CharField(max_length=100, blank=True, null=True)
    text = models.CharField(max_length=100, blank=True, null=True)
    link = models.URLField(blank=True, null=True)

    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Image"


class ShopbottomBanner(models.Model):
    image = models.ImageField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Image"


class Reviews(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    rating = models.IntegerField(blank=False, null=True)
    review = models.TextField()
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Reviews'


class Contact(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    subject = models.CharField(max_length=30)

templates/banner2.html
{% load static %}

	<section class="banner2 p-t-150 p-b-150">
		<div class="container">
			<div class="row">
				
				{% for item  in shoptop %}
					
			
					
				<div class="col-sm-10 col-md-8 col-lg-6 m-l-r-auto p-t-15 p-b-15">
					<div class="hov-img-zoom pos-relative">
						<img src="{{item.image.url}}" alt="IMG-BANNER">

						<div class="ab-t-l sizefull flex-col-c-m p-l-15 p-r-15">
							<span class="m-text9 p-t-45 fs-20-sm">
						{{item.title}}
							</span>

							<h3 class="l-text1 fs-35-sm">
								{{item.text}}
							</h3>

							<a href="{{item.link}}" class="s-text4 btn btn-small p-t-10  p-b-10">
								View Collection
							</a>
						</div>
					</div>
				</div>
					{% endfor %}
			{% for item  in shopbottom %}
				<div class="col-sm-10 col-md-8 col-lg-6 m-l-r-auto p-t-15 p-b-15">
					<div class="bgwhite hov-img-zoom pos-relative p-b-20per-ssm">
						<img src="{{item.image.url}}" alt="IMG-BANNER">

					
					</div>
				</div>
							{% endfor %}
			</div>
		</div>
	</section>

templates/banner4.html
{% load static %}

{% for item in homeside %}
    
<!-- Banner2 -->
	<div class="banner2 bg5  p-t-250 p-b-250 bg-img1"  style="background: url({{item.image.url}}) no-repeat center center/cover;">
		<div class="container">
			<div class="flex-w flex-r-m flex-c-xl">
				<div class="p-t-15 p-b-15 w-size28">
					<div class="bgwhite hov-img-zoom pos-relative p-b-20per-ssm">
		

				
					</div>
				</div>
			</div>
		</div>
	</div>

    
{% endfor %}
    

templates/confirmation.html
{% extends 'base.html' %}
{%  load static %}
{% block css %}
<title>Paystack Success - Jane's Fashion</title>

{% endblock css %}
{% block content %}

<!-- Page Wrapper -->
<section class="page-wrapper success-msg">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="block text-center">


          <h2 class="text-center fs-24 ">Thank you! For your payment</h2> <br>
          <p class="fs-18">We will contact you shortly <br>
            You are amazing</p>
          <img src="{% static 'images/success.svg' %}" alt=""> <br>
          <a href="{% url 'core:shop' %}" class="btn btn-main mt-20">Continue Shopping</a>
        </div>
      </div>
    </div>
  </div>
</section><!-- /.page-warpper -->
{% endblock content %}

templates/forget-password.html
{% extends 'base.html' %}


{% block content %}
<section class="forget-password-page account">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="block text-center">
          <a class="logo" href="index.html">
            <img src="images/logo.png" alt="">
          </a>
          <h2 class="text-center">Welcome Back</h2>
          <form class="text-left clearfix">
            <p>Please enter the email address for your account. <br> A verification code will be sent to you. Once you have received the verification code, you will be able to choose a new password for your account.</p>
            <div class="form-group">
              <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Account email address">
            </div>
            <div class="text-center">
              <button type="submit" class="btn btn-main text-center">Request password reset</button>
            </div>
          </form>
          <p class="mt-20"><a href="login.html">Back to log in</a></p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/product-single.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load humanize %}

{% load static %}

{% load crispy_forms_tags %}
{% block css %}

<title> {{product.title|title}} - Jane's Fashion </title>
{% endblock css %}

{% block content %}
<section class="single-product">
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<ol class="breadcrumb">
					<li><a href="{% url 'core:home' %}">Home</a></li>
					<li><a href="{% url 'core:shop' %}">Shop</a></li>
					<li class="active">{{product.title|title}}</li>
				</ol>
			</div>
			<div class="col-md-6">

			</div>
		</div>
		<div class="row mt-20">
			<div class="col-md-5">
				<div class="single-product-slider">
					<div id='carousel-custom' class='carousel slide' data-ride='carousel'>
						<div class='carousel-outer'>
							<!-- me art lab slider -->
							<div class='carousel-inner '>
								{% if product.image %}
								<div class='item active'>

									<img src='{{product.image.url}}' data-zoom-image="{{product.image.url}}"
										alt="Jane's Fashion {{product.title|title}}" />
								</div>
								{% endif %}
								{% if product.image_1 %}
								<div class='item'>
									<img src='{{product.image_1.url}}' alt="Jane's Fashion {{product.title|title}}"
										data-zoom-image="{{product.image_1.url}}" />
								</div>
								{% endif %}
								{% if product.image_2 %}
								<div class='item'>
									<img src='{{product.image_2.url}}' alt="Jane's Fashion {{product.title|title}}"
										data-zoom-image="{{product.image_2.url}}" />
								</div>
								{% endif %}
								{% if product.image_3 %}
								<div class='item'>
									<img src='{{product.image_3.url}}' alt="Jane's Fashion {{product.title|title}}"
										data-zoom-image="{{product.image_3.url}}' %}" />
								</div> {% endif %}

								{% if product.image_4 %}
								<div class='item'>
									<img src='{{product.image_4.url}}' alt="Jane's Fashion {{product.title|title}}"
										data-zoom-image="{{product.image_4.url}}' %}" />
								</div>
								{% endif %}

							</div>

							<!-- sag sol -->
							<a class='left carousel-control' href='#carousel-custom' data-slide='prev'>
								<i class="tf-ion-ios-arrow-left"></i>
							</a>
							<a class='right carousel-control' href='#carousel-custom' data-slide='next'>
								<i class="tf-ion-ios-arrow-right"></i>
							</a>
						</div>

						<!-- thumb -->
						<ol class='carousel-indicators mCustomScrollbar meartlab'>
							{% if product.image %}
							<li data-target='#carousel-custom' data-slide-to='0' class='active'>
								<img src='{{product.image.url}}' alt="Jane's Fashion {{product.title|title}}" />
							</li>
							{% endif %}
							{% if product.image_1 %}
							<li data-target='#carousel-custom' data-slide-to='1'>
								<img src='{{product.image_1.url}}' alt="Jane's Fashion {{product.title|title}}" />
							</li>
							{% endif %}
							{% if product.image_2 %}
							<li data-target='#carousel-custom' data-slide-to='2'>
								<img src='{{product.image_2.url}}' alt="Jane's Fashion {{product.title|title}}" />
							</li>
							{% endif %}
							{% if product.image_3 %}
							<li data-target='#carousel-custom' data-slide-to='3'>
								<img src='{{product.image_3.url}}' alt="Jane's Fashion {{product.title|title}}" />
							</li>
							{% endif %}
							{% if product.image_4 %}
							<li data-target='#carousel-custom' data-slide-to='4'>
								<img src='{{product.image_4.url}}' alt="Jane's Fashion {{product.title|title}}" />
							</li>
							{% endif %}
						</ol>
					</div>
				</div>
			</div>
			<div class="col-md-7">
				<div class="single-product-details">
					<div class="product-category">
						<span>Categories:</span>
						<ul>
							<li><a href="{{product.category.get_category_url}}">{{product.category.name|title}}</a></li>

						</ul>
					</div>
					<h2 class='fs-34  p-t-8 p-b-8'>{{product.title|title}}</h2>
					<h4 class="product-price fs-20 p-t-8"> &#8358; {{product.price|intcomma}}</h4>

					<p class="product-description mt-20">
						{{product.description|safe}}
					</p>

					<div class="color-swatches m-t-16">
						<span>Available Color:</span>
						<ul>
							{% if product.color ==  'black' %}
							<li>
								<a class="swatch-black"></a>
							</li>
							{% endif %}
							{% if product.color ==  'white' %}
							<li>
								<a class="swatch-white"></a>
							</li>
							{% endif %}
							{% if product.color ==  'red' %}
							<li>
								<a class="swatch-red"></a>
							</li> {% endif %}
							{% if product.color ==  'green' %}
							<li>
								<a class="swatch-green"></a>
							</li> {% endif %}
							{% if product.color ==  'purple' %}
							<li>
								<a class="swatch-purple"></a>
							</li> {% endif %}
							{% if product.color ==  'brown' %}
							<li>
								<a class="swatch-brown"></a>
							</li> {% endif %}
							{% if product.color == 'pink' %}
							<li>
								<a class="swatch-pink"></a>
							</li> {% endif %}
						</ul>
					</div>

					{% comment %} <div class="product-size">
						<span>Size:</span>
						<select class="form-control">
							<option>S</option>
							<option>M</option>
							<option>L</option>
							<option>XL</option>
						</select>
					</div> {% endcomment %}
					<a href="{{product.get_add_to_cart_url}}" class="btn fs-16 btn-main mt-20"> <i
							class="tf-ion-ios-cart"></i> Buy Now</a>
					<a href="{{product.get_wishlist_product}}" class="btn btn-solid-border mt-20"> <i
							class="fs-16 tf-ion-ios-heart"></i> Save For Later </a>
				</div>

			</div>
		</div>
		<div class="row">
			<div class="col-xs-12">
				<div class="tabCommon mt-20">
					<ul class="nav nav-tabs">
						<li class="active"><a data-toggle="tab" href="#details" aria-expanded="true">Details</a></li>
						<li class=""><a data-toggle="tab" href="#reviews" aria-expanded="false">

								{% if product.get_review_count == 1 or product.get_review_count == 0 %}Review{% else %}Reviews
								{% endif %} ({{product.get_review_count}})</a></li>
						<li class=""><a data-toggle="tab" href="#leave-reviews" aria-expanded="false">Drop Review
								Lovelies</a></li>
					</ul>
					<div class="tab-content patternbg">
						<div id="details" class="tab-pane  fade active in">
							<h4 class="fs-34  p-b-8">Product Description</h4>
							<p class="fs-18"> {{product.description|safe}}</p>
							{% if product.size_chart %}
							<div class="product-quantity">

								<h2>Size Chart:</h2>
								<div class="product-quantity-slider">
									<img class="product-chart" src="{{product.size_chart.url}}" alt="">
								</div>

							</div>
							{%endif %}
						</div>
						<div id="reviews" class="tab-pane fade">
							<div class="post-comments">
								<ul class="media-list comments-list m-bot-50 clearlist">
									<!-- Comment Item start-->
									{% for review in product.get_reviews%}
									<li class="media">

										<a class="pull-left" href="#">

										</a>

										<div class="media-body">
											<div class="comment-info">
												<h4 class="comment-author">
													<a>{{review.user|title}}</a>

												</h4>
												<h6 class="fs-16">{{review.time}}</h6>

											</div>

											<p>
												{{review.review|safe}}
											</p>
										</div>

									</li>
									{%empty%}
									<p>No review yet</p>
									{% endfor %}
									<!-- End Comment Item -->


								</ul>
							</div>


						</div>
						<div id="leave-reviews" class="tab-pane fade">


							<div class="post-comments-form">
								<h3 class="post-sub-heading">Leave Your Reviews</h3>
								{% if request.user.is_authenticated %}
								<form method="post" id="form" role="form">
									{% csrf_token %}
									<div class="row">



										<!-- Comment -->
										<div class="form-group col-md-12">

											{{form|crispy}}
										</div>

										<!-- Send Button -->
										<div class="form-group col-md-12">
											<button type="submit" class="btn btn-small btn-main ">
												Send comment
											</button>
										</div>


									</div>

								</form>
								{% else %}

								<a href="{% url 'account_login' %}" class="btn btn-main">Login To Review</a>
								{% endif %}
							</div>


						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="section">

</section>

<section class="products related-products section">
	<div class="container">
		<div class="row">
			<div class="title text-center">
				<h2 class="fs-24">Related <span class="colored-jane">Products</span></h2>
			</div>
		</div>
		<div class="row"> {% for item in trip_related%}
			<div class="col-md-3">
				<div class="product-item">
					<div class="product-thumb">
						<span class="bage">Sale</span>
						{% thumbnail item.image '300x300' crop="center" as jane %}
						<img class="img-responsive" src="{{jane.url}}" width="{{jane.width}}" height="{{jane.height}}"
							alt="jane's Fashion {{item.title|title}}" />
						{% endthumbnail %} <div class="preview-meta">
							<ul>

								<li>
									<a href="{{item.get_absolute_url}}"><i class="tf-ion-eye"></i></a>
								</li>
							</ul>
						</div>
					</div>
					<div class="product-content">
						<h4><a href="{{item.get_absolute_url}}">{{item.title|title}}</a></h4>
						<p class="price">&#8358;{{item.price|intcomma}}</p>
					</div>
				</div>
			</div>
			{% endfor %}

		</div>
	</div>
</section>

{% include 'notification.html' %}





{% endblock content %}